version: "3.9"

services:
  database_tests_challenge:
    image: postgres
    container_name: database_tests_challenge
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres
    #network_mode: host

volumes:
  pgdata:
    driver: local
